image: maven:latest

stages:
  - build
  - test
  - deploy

maven-build:
  image: maven:latest
  stage: build
  script: "mvn package -B"

maven-test:
  image: maven:latest
  stage: test
  script: "mvn test -B"

deploy:
  stage: deploy
  image: maven:latest
  script: "mvn clean heroku:deploy"
  only:
  - master
