image: maven:latest

stages:
  - build
  - test
  - build_image
  - deploy

maven-build:
  image: maven:latest
  stage: build
  script: "mvn package -B"

maven-test:
  image: maven:latest
  stage: test
  script: "mvn test -B"

build-image:
  image: docker:latest
  stage: build_image
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
#  only:
#    - master

deploy:
  stage: deploy
  image: maven:latest
  script: "mvn clean heroku:deploy"
  only:
  - master
