version: '3'
services:
  mysql:
    image: mysql
    ports:
      - '3333:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root_pa$$
      - MYSQL_DATABASE=crm_production

  server:
    build: .
    container_name: crm-backend
    ports:
      - '8888:8080'
    command: /bin/sh -c "java -jar target/crm*.jar"

