version: '3'
services:
  mysql:
    image: mysql
    container_name: crm-backend-mysql
    ports:
      - '3333:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=crm_production

  server:
    # build: .
    image: registry.gitlab.com/crm-expedicia/backend:latest
    container_name: crm-backend
    ports:
      - '8888:8080'
    command: /bin/sh -c "mvn clean package -Pdocker && java -jar target/crm*.jar"

