stages:
  - build
  - test
  - deploy

maven-build:
  image: maven:latest
  stage: build
  script: "mvn package spring-boot:repackage"

maven-test:
  image: maven:latest
  stage: test
  script: "mvn test -B"

deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=crm-expedicia-backend --api-key=$HEROKU_API_KEY
  only:
  - master
