spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dbUrl}
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: ${dbUrl}